### ISSUE TITLE
Suggestion: Drop support for python versions < 3.7

### ISSUE THREAD

**Issue by aqeelat** [nvictus/priority-queue-dictionary#22]
The CI only covers versions 3.8 and above, and 3.6 reached EOL a while ago.
I didn't actually go through the code but I noticed that the package has the classifiers for the old versions.

**Comment by nvictus** [comment]
Since we only depend on the standard library, I'm fine with supporting a wider range of Python versions. Though Python 2 needs to go. WIP #23 

I'm thinking of covering back to 3.6 in the next minor release, unless there's a good reason not to. See this [comment](https://github.com/manzt/anywidget/issues/166#issuecomment-1609746765).

**Comment by aqeelat** [comment]
Great work!

I'm not sure if Python 3.6 is widely used because most people I know are on 3.7 and above (circumstantial). Even though 3.7 is EOL as of a few days ago, I think it will be a while before projects migrate from it. Regardless, I think you're right to only remove Python 2 in your PR.

I would recommend you run https://github.com/asottile/pyupgrade against the repo as well.

**Comment by nvictus** [comment]
I also migrated to `pyproject.toml` and it proved too painful to make editable installs work on py36 in CI. So, in the end, I went ahead and pinned it to >=3.7. Thanks for your help.
